### ISSUE TITLE
Accept a whitelist of origins?

### ISSUE THREAD

**Issue by callumlocke** [evert0n/koa-cors#26]
Could `origin` take an array of allowed origins?

**Comment by evert0n** [comment]
No, seems the best approach would be to you to have a whitelist and with a custom function for origin return that domain based on the request.
http://stackoverflow.com/questions/1653308/access-control-allow-origin-multiple-origin-domains

Like in this example instead of a start "*" you can have your own function:
https://github.com/evert0n/koa-cors/blob/master/examples/custom-options.js
https://github.com/evert0n/koa-cors#origin

**Comment by callumlocke** [comment]
I know there's a way to do it manually, but involves writing a custom function every time you want to do this.

This seems like a very common use case, so why not make koa-cors do it automatically when an array is given for `origin`?

**Comment by rosshadden** [comment]
It's worth noting the express cors project, which this is quite possibly based on, supports arrays: https://github.com/expressjs/cors#configuration-options
